"""empty message

Revision ID: 613ff13d9559
Revises: a05f6d1ff3f9
Create Date: 2023-11-30 01:52:50.904427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613ff13d9559'
down_revision = 'a05f6d1ff3f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('user_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_unique_constraint(None, ['user_name'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')
        batch_op.drop_column('user_name')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
