"""empty message

Revision ID: 9498c316913c
Revises: c2d1f714a1ed
Create Date: 2024-02-08 00:45:18.694456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9498c316913c'
down_revision = 'c2d1f714a1ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('second_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('user_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('age_user', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('country_user', sa.String(length=120), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('country_user')
        batch_op.drop_column('age_user')
        batch_op.drop_column('user_name')
        batch_op.drop_column('second_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
