"""empty message

Revision ID: c2d1f714a1ed
Revises: 2acf5f9d31e7
Create Date: 2024-02-08 00:32:38.614509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d1f714a1ed'
down_revision = '2acf5f9d31e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_constraint('user_name_key', type_='unique')
        batch_op.drop_constraint('user_user_name_key', type_='unique')
        batch_op.drop_column('user_id')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')
        batch_op.drop_column('name')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.create_unique_constraint('user_user_name_key', ['user_name'])
        batch_op.create_unique_constraint('user_name_key', ['name'])
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
